version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  currency_service:
    build: ./currency_service
    container_name: currency_service
    depends_on:
      - redis

  bot_service:
    build: ./bot_service
    container_name: bot_service
    depends_on:
      - redis
    env_file:
      - .env
